export const INITIAL_INGREDIENTS = 'INITIAL_INGREDIENTS';
export const INITIAL_INGREDIENTS_FAILED = 'INITIAL_INGREDIENTS_FAILED';
export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const GET_ORDERS = 'GET_ORDERS';
export const GET_ORDERS_FAILED = 'GET_ORDERS_FAILED';