// Burger Builder Container
export const GET_INITIAL_INGREDIENTS = 'GET_INITIAL_INGREDIENTS'
export const INITIAL_INGREDIENTS = 'INITIAL_INGREDIENTS';
export const INITIAL_INGREDIENTS_FAILED = 'INITIAL_INGREDIENTS_FAILED';
export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const RESET_INGREDIENTS = 'RESET_INGREDIENTS';

// Orders Container
export const INIT_GET_ORDERS = 'INIT_GET_ORDERS';
export const GET_ORDERS = 'GET_ORDERS';
export const GET_ORDERS_FAILED = 'GET_ORDERS_FAILED';

// Contact Data Container
export const PURCHASE_HANDLER = 'PURCHASE_HANDLER';
export const PURCHASE_INIT = 'PURCHASE_INIT';
export const PURCHASE_ORDER_START = 'PURCHASE_BURGER_START';
export const PURCHASE_ORDER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
export const PURCHASE_ORDER_FAIL = 'PURCHASE_BURGER_FAIL';

// Auth Start
export const AUTH_START = 'AUTH_START';
export const AUTH_USER = 'AUTH_USER';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT';
export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE'
export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_SET_REDIRECT_PATH = 'AUTH_SET_REDIRECT_PATH';